import Head from 'next/head';
import ContactSection from './../../components/contact/ContactSection';

const Contact = () => {
  return (
    <>
      <Head>
        <title>Kontakt</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <ContactSection />
      </main>
    </>
  );
};

export default Contact;
