import Head from 'next/head';
import GdprSection from './../../components/gdpr/GdprSection';
import Layout from './../../components/layout/Layout';

const Gdpr = () => {
  return (
    <>
      <Head>
        <title>Ochrana osobních údajů</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <GdprSection />
      </Layout>
    </>
  );
};

export default Gdpr;
