import Head from 'next/head';
import GdprSection from './../../components/gdpr/GdprSection';

const Gdpr = () => {
  return (
    <>
      <Head>
        <title>Ochrana osobních údajů</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <GdprSection />
    </>
  );
};

export default Gdpr;
