import Head from 'next/head';
import CardsSection from './../../components/about-watsu/CardsSection';
import WaveAnimation from './../../components/about-watsu/WaveAnimation';

const AboutWatsu = () => {
  return (
    <>
      <Head>
        <title>O watsu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <CardsSection />
      <WaveAnimation />
    </>
  );
};

export default AboutWatsu;
