import Head from 'next/head';
import CardsSection from './../../components/about-watsu/CardsSection';
const AboutWatsu = () => {
  return (
    <>
      <Head>
        <title>O watsu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <CardsSection />
      </main>
    </>
  );
};

export default AboutWatsu;
