import Head from 'next/head';

const AboutWatsu = () => {
  return (
    <>
      <Head>
        <title>O watsu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main></main>
    </>
  );
};

export default AboutWatsu;
