import Head from 'next/head';

const Contraindication = () => {
  return (
    <>
      <Head>
        <title>Kontraindikace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main></main>
    </>
  );
};

export default Contraindication;
