import Head from 'next/head';

const Therapy = () => {
  return (
    <>
      <Head>
        <title>Průběh terapie</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main></main>
    </>
  );
};

export default Therapy;
