import Head from 'next/head';

const Effects = () => {
  return (
    <>
      <Head>
        <title>Účinky</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main></main>
    </>
  );
};

export default Effects;
