import Head from 'next/head';
import styles from '../styles/Home.module.scss';
const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className={styles.test}>test</p>
      </main>{' '}
    </>
  );
};

export default Home;
