import Head from 'next/head';
import IntroSection from './../components/homepage/IntroSection';

const Home = () => {
  return (
    <>
      <Head>
        <title>Watsu úvod</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <IntroSection />
      </main>{' '}
    </>
  );
};

export default Home;
