import Head from 'next/head';
import NewsletterSection from '../../components/reservation/NewsletterSection';

const NewsletterForm = () => {
  return (
    <>
      <Head>
        <title>Email o termínech</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <NewsletterSection />
      </main>
    </>
  );
};

export default NewsletterForm;
