import Head from 'next/head';
import NewsletterSection from '../../components/reservation/NewsletterSection';
import Layout from './../../components/layout/Layout';

const NewsletterForm = () => {
  return (
    <>
      <Head>
        <title>Email o termínech</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <NewsletterSection />
      </Layout>
    </>
  );
};

export default NewsletterForm;
