import Head from 'next/head';
import TermsCard from './../../components/reservation/TermsCard';

const Reservation = () => {
  return (
    <>
      <Head>
        <title>Rezervovat termín</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <TermsCard />
      </main>
    </>
  );
};

export default Reservation;
