import Head from 'next/head';
import ReservationConfirmSection from '../../components/reservation/ReservationConfirmSection';

const ReservationConfirm = () => {
  return (
    <>
      <Head>
        <title>Potvrzení rezervace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <ReservationConfirmSection />
      </main>
    </>
  );
};

export default ReservationConfirm;
